name: payment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.3 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_credit_card: ^4.1.0
  flutter_inappwebview: ^6.1.5
  flutter_paypal_payment: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_stripe: ^9.5.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
